/*
 * kernd_init.c - 'kernd init' subcommand implementation
 *
 * Generates random credentials and writes the initial config file.
 */

#include "kernd_init.h"
#include "kernd_log.h"
#include "kern.h"

#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>

/* Base64url alphabet (no padding) */
static const char b64url_table[] =
    "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_";

static int read_urandom(unsigned char *buf, size_t len) {
    FILE *f = fopen("/dev/urandom", "rb");
    if (!f) return -1;
    size_t n = fread(buf, 1, len, f);
    fclose(f);
    return n == len ? 0 : -1;
}

static char *hex_encode(const unsigned char *data, size_t len) {
    char *out = malloc(len * 2 + 1);
    if (!out) return NULL;
    for (size_t i = 0; i < len; i++) {
        snprintf(out + i * 2, 3, "%02x", data[i]);
    }
    out[len * 2] = '\0';
    return out;
}

static char *base64url_encode(const unsigned char *data, size_t len) {
    size_t out_len = ((len * 4) + 2) / 3;
    char *out = malloc(out_len + 1);
    if (!out) return NULL;

    size_t i = 0, j = 0;
    while (i < len) {
        uint32_t a = (i < len) ? data[i++] : 0;
        uint32_t b = (i < len) ? data[i++] : 0;
        uint32_t c = (i < len) ? data[i++] : 0;
        uint32_t triple = (a << 16) | (b << 8) | c;

        size_t remaining = len - (i - 3);
        if (j < out_len) out[j++] = b64url_table[(triple >> 18) & 0x3F];
        if (j < out_len) out[j++] = b64url_table[(triple >> 12) & 0x3F];
        if (remaining > 1 && j < out_len) out[j++] = b64url_table[(triple >> 6) & 0x3F];
        if (remaining > 2 && j < out_len) out[j++] = b64url_table[triple & 0x3F];
    }
    out[j] = '\0';
    return out;
}

static int ensure_parent_dir(const char *path) {
    char *tmp = strdup(path);
    if (!tmp) return -1;

    /* Find last slash */
    char *last_slash = strrchr(tmp, '/');
    if (!last_slash || last_slash == tmp) {
        free(tmp);
        return 0; /* No parent dir needed or root */
    }
    *last_slash = '\0';

    /* Try to create the directory (recursive for one level) */
    if (mkdir(tmp, 0755) == -1 && errno != EEXIST) {
        /* Try creating parent of parent */
        char *parent_slash = strrchr(tmp, '/');
        if (parent_slash && parent_slash != tmp) {
            *parent_slash = '\0';
            if (mkdir(tmp, 0755) == -1 && errno != EEXIST) {
                free(tmp);
                return -1;
            }
            *parent_slash = '/';
            if (mkdir(tmp, 0755) == -1 && errno != EEXIST) {
                free(tmp);
                return -1;
            }
        }
    }

    free(tmp);
    return 0;
}

int kernd_init_run(const char *config_path) {
    const char *path = config_path ? config_path : "/etc/kernd/dashboard.toml";

    /* Generate 32-byte random secret (hex-encoded = 64 chars) */
    unsigned char secret_bytes[32];
    if (read_urandom(secret_bytes, sizeof(secret_bytes)) != 0) {
        kernd_log_error("failed to read from /dev/urandom");
        return -1;
    }
    char *secret_hex = hex_encode(secret_bytes, sizeof(secret_bytes));
    if (!secret_hex) {
        kernd_log_error("failed to hex-encode secret");
        return -1;
    }

    /* Generate 16-byte random admin password (base64url-encoded) */
    unsigned char pw_bytes[16];
    if (read_urandom(pw_bytes, sizeof(pw_bytes)) != 0) {
        kernd_log_error("failed to read from /dev/urandom");
        free(secret_hex);
        return -1;
    }
    char *password = base64url_encode(pw_bytes, sizeof(pw_bytes));
    if (!password) {
        kernd_log_error("failed to base64url-encode password");
        free(secret_hex);
        return -1;
    }

    /* Hash the password */
    char *pw_hash = kern_password_hash(password);
    if (!pw_hash) {
        kernd_log_error("failed to hash admin password");
        free(secret_hex);
        free(password);
        return -1;
    }

    /* Ensure parent directory exists */
    if (ensure_parent_dir(path) != 0) {
        kernd_log_error("failed to create directory for %s", path);
        free(secret_hex);
        free(password);
        free(pw_hash);
        return -1;
    }

    /* Write config file */
    FILE *f = fopen(path, "w");
    if (!f) {
        kernd_log_error("failed to open %s for writing: %s", path, strerror(errno));
        free(secret_hex);
        free(password);
        free(pw_hash);
        return -1;
    }

    fprintf(f, "# kernd dashboard configuration\n");
    fprintf(f, "# Generated by 'kernd init'\n\n");
    fprintf(f, "[admin]\n");
    fprintf(f, "port = 8443\n");
    fprintf(f, "password_hash = \"%s\"\n\n", pw_hash);
    fprintf(f, "[http]\n");
    fprintf(f, "port = 80\n\n");
    fprintf(f, "[https]\n");
    fprintf(f, "port = 443\n\n");
    fprintf(f, "[paths]\n");
    fprintf(f, "data_dir = \"/var/lib/kernd\"\n");
    fprintf(f, "log_dir = \"/var/log/kernd\"\n\n");
    fprintf(f, "[security]\n");
    fprintf(f, "dashboard_secret = \"%s\"\n", secret_hex);

    fclose(f);

    /* Print credentials to stdout */
    printf("kernd initialized successfully!\n\n");
    printf("Config written to: %s\n\n", path);
    printf("Admin credentials (save these - they cannot be recovered):\n");
    printf("  Password: %s\n\n", password);
    printf("Dashboard secret: %s\n", secret_hex);

    free(secret_hex);
    free(password);
    free(pw_hash);
    return 0;
}
