/*
 * kern_shard_static.c - Embedded kern-shards.js content
 *
 * This file embeds the kern-shards.js client runtime as a C string
 * constant so the framework can serve it without reading from disk.
 * The source lives at static/kern-shards.js for development.
 */

#include "kern.h"

#include <string.h>

static const char kern_shards_js_data[] =
    "/**\n"
    " * kern-shards.js - Client-side runtime for kern shards\n"
    " *\n"
    " * Provides HTMX-style server-rendered interactivity by scanning\n"
    " * for [data-shard] elements and fetching HTML fragments from the server.\n"
    " *\n"
    " * Vanilla ES2020, no dependencies, < 12KB.\n"
    " */\n"
    "(function() {\n"
    "    \"use strict\";\n"
    "\n"
    "    var SHARD_ATTR = \"data-shard\";\n"
    "    var TARGET_ATTR = \"data-shard-target\";\n"
    "    var SWAP_ATTR = \"data-shard-swap\";\n"
    "    var TRIGGER_ATTR = \"data-shard-trigger\";\n"
    "    var METHOD_ATTR = \"data-shard-method\";\n"
    "    var CONFIRM_ATTR = \"data-shard-confirm\";\n"
    "    var INDICATOR_ATTR = \"data-shard-indicator\";\n"
    "    var HEADERS_ATTR = \"data-shard-headers\";\n"
    "\n"
    "    var LOADING_CLASS = \"kern-loading\";\n"
    "\n"
    "    function getDefaultTrigger(el) {\n"
    "        var tag = el.tagName.toLowerCase();\n"
    "        if (tag === \"form\") return \"submit\";\n"
    "        if (tag === \"input\" || tag === \"textarea\" || tag === \"select\") return \"input\";\n"
    "        return \"click\";\n"
    "    }\n"
    "\n"
    "    function getDefaultMethod(el) {\n"
    "        var tag = el.tagName.toLowerCase();\n"
    "        if (tag === \"form\") return \"POST\";\n"
    "        return \"GET\";\n"
    "    }\n"
    "\n"
    "    function getTarget(el) {\n"
    "        var selector = el.getAttribute(TARGET_ATTR);\n"
    "        if (!selector) return el;\n"
    "        return document.querySelector(selector) || el;\n"
    "    }\n"
    "\n"
    "    function getSwapMode(el) {\n"
    "        return el.getAttribute(SWAP_ATTR) || \"inner\";\n"
    "    }\n"
    "\n"
    "    function dispatch(target, name, detail) {\n"
    "        var event = new CustomEvent(name, {\n"
    "            bubbles: true,\n"
    "            cancelable: true,\n"
    "            detail: detail || {}\n"
    "        });\n"
    "        return target.dispatchEvent(event);\n"
    "    }\n"
    "\n"
    "    function showIndicator(el) {\n"
    "        var selector = el.getAttribute(INDICATOR_ATTR);\n"
    "        if (!selector) return null;\n"
    "        var indicator = document.querySelector(selector);\n"
    "        if (indicator) indicator.classList.add(LOADING_CLASS);\n"
    "        return indicator;\n"
    "    }\n"
    "\n"
    "    function hideIndicator(indicator) {\n"
    "        if (indicator) indicator.classList.remove(LOADING_CLASS);\n"
    "    }\n"
    "\n"
    "    function swap(target, mode, html) {\n"
    "        switch (mode) {\n"
    "            case \"outer\":\n"
    "                target.outerHTML = html;\n"
    "                break;\n"
    "            case \"before\":\n"
    "                target.insertAdjacentHTML(\"beforebegin\", html);\n"
    "                break;\n"
    "            case \"after\":\n"
    "                target.insertAdjacentHTML(\"afterend\", html);\n"
    "                break;\n"
    "            case \"append\":\n"
    "                target.insertAdjacentHTML(\"beforeend\", html);\n"
    "                break;\n"
    "            case \"prepend\":\n"
    "                target.insertAdjacentHTML(\"afterbegin\", html);\n"
    "                break;\n"
    "            case \"inner\":\n"
    "            default:\n"
    "                target.innerHTML = html;\n"
    "                break;\n"
    "        }\n"
    "    }\n"
    "\n"
    "    function serializeForm(form) {\n"
    "        var formData = new FormData(form);\n"
    "        var params = new URLSearchParams();\n"
    "        formData.forEach(function(value, key) {\n"
    "            params.append(key, value);\n"
    "        });\n"
    "        return params.toString();\n"
    "    }\n"
    "\n"
    "    function getExtraHeaders(el) {\n"
    "        var raw = el.getAttribute(HEADERS_ATTR);\n"
    "        if (!raw) return {};\n"
    "        try {\n"
    "            return JSON.parse(raw);\n"
    "        } catch (e) {\n"
    "            return {};\n"
    "        }\n"
    "    }\n"
    "\n"
    "    function doFetch(el) {\n"
    "        var url = el.getAttribute(SHARD_ATTR);\n"
    "        if (!url) return;\n"
    "\n"
    "        var confirmMsg = el.getAttribute(CONFIRM_ATTR);\n"
    "        if (confirmMsg && !window.confirm(confirmMsg)) return;\n"
    "\n"
    "        var target = getTarget(el);\n"
    "        var mode = getSwapMode(el);\n"
    "        var method = (el.getAttribute(METHOD_ATTR) || getDefaultMethod(el)).toUpperCase();\n"
    "        var extraHeaders = getExtraHeaders(el);\n"
    "\n"
    "        if (!dispatch(target, \"kern:before-request\", { url: url, method: method })) return;\n"
    "\n"
    "        var indicator = showIndicator(el);\n"
    "\n"
    "        var headers = { \"X-Kern-Shard\": \"true\" };\n"
    "        Object.keys(extraHeaders).forEach(function(k) {\n"
    "            headers[k] = extraHeaders[k];\n"
    "        });\n"
    "\n"
    "        var options = { method: method, headers: headers };\n"
    "\n"
    "        if (method !== \"GET\" && method !== \"HEAD\") {\n"
    "            var tag = el.tagName.toLowerCase();\n"
    "            if (tag === \"form\") {\n"
    "                headers[\"Content-Type\"] = \"application/x-www-form-urlencoded\";\n"
    "                options.body = serializeForm(el);\n"
    "            }\n"
    "        }\n"
    "\n"
    "        fetch(url, options)\n"
    "            .then(function(response) {\n"
    "                return response.text();\n"
    "            })\n"
    "            .then(function(html) {\n"
    "                dispatch(target, \"kern:after-request\", { url: url, html: html });\n"
    "                swap(target, mode, html);\n"
    "                dispatch(target, \"kern:swap\", { url: url, mode: mode });\n"
    "                scanElement(mode === \"outer\" ? document.body : target);\n"
    "            })\n"
    "            .catch(function(err) {\n"
    "                dispatch(target, \"kern:after-request\", { url: url, error: err });\n"
    "            })\n"
    "            .finally(function() {\n"
    "                hideIndicator(indicator);\n"
    "            });\n"
    "    }\n"
    "\n"
    "    function attachTrigger(el) {\n"
    "        if (el._kernShardBound) return;\n"
    "        el._kernShardBound = true;\n"
    "\n"
    "        var trigger = el.getAttribute(TRIGGER_ATTR) || getDefaultTrigger(el);\n"
    "\n"
    "        if (trigger === \"load\") {\n"
    "            doFetch(el);\n"
    "            return;\n"
    "        }\n"
    "\n"
    "        if (trigger === \"revealed\") {\n"
    "            var observer = new IntersectionObserver(function(entries, obs) {\n"
    "                entries.forEach(function(entry) {\n"
    "                    if (entry.isIntersecting) {\n"
    "                        obs.unobserve(entry.target);\n"
    "                        doFetch(entry.target);\n"
    "                    }\n"
    "                });\n"
    "            }, { threshold: 0 });\n"
    "            observer.observe(el);\n"
    "            return;\n"
    "        }\n"
    "\n"
    "        el.addEventListener(trigger, function(e) {\n"
    "            if (trigger === \"submit\") e.preventDefault();\n"
    "            doFetch(el);\n"
    "        });\n"
    "    }\n"
    "\n"
    "    function scanElement(root) {\n"
    "        if (!root) return;\n"
    "        var elements = root.querySelectorAll(\"[\" + SHARD_ATTR + \"]\");\n"
    "        elements.forEach(function(el) {\n"
    "            attachTrigger(el);\n"
    "        });\n"
    "        if (root.hasAttribute && root.hasAttribute(SHARD_ATTR)) {\n"
    "            attachTrigger(root);\n"
    "        }\n"
    "    }\n"
    "\n"
    "    function init() {\n"
    "        scanElement(document.body);\n"
    "\n"
    "        var observer = new MutationObserver(function(mutations) {\n"
    "            mutations.forEach(function(mutation) {\n"
    "                mutation.addedNodes.forEach(function(node) {\n"
    "                    if (node.nodeType === 1) {\n"
    "                        scanElement(node);\n"
    "                    }\n"
    "                });\n"
    "            });\n"
    "        });\n"
    "\n"
    "        observer.observe(document.body, { childList: true, subtree: true });\n"
    "    }\n"
    "\n"
    "    if (document.readyState === \"loading\") {\n"
    "        document.addEventListener(\"DOMContentLoaded\", init);\n"
    "    } else {\n"
    "        init();\n"
    "    }\n"
    "})();\n"
    "\n"
;

const char *kern_shards_js(void) {
    return kern_shards_js_data;
}

size_t kern_shards_js_len(void) {
    return sizeof(kern_shards_js_data) - 1;
}

kern_response_t *kern_shards_js_serve(kern_req_t *req) {
    (void)req;

    kern_response_t *res = kern_response_new(200);
    if (!res) return NULL;

    kern_response_header(res, "Content-Type", "application/javascript; charset=utf-8");
    kern_response_header(res, "Cache-Control", "public, max-age=86400");
    kern_response_body(res, kern_shards_js_data, sizeof(kern_shards_js_data) - 1);

    return res;
}
